       //------------------------------------------------------------------------------
       // <auto-generated>
       //     這段程式碼是由工具產生的。
       //     執行階段版本:4.0.30319.4641
       //
       //     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
       //     變更將會遺失。
       // </auto-generated>
       //------------------------------------------------------------------------------

       namespace LeagueSharp.Common.Properties {
       using System;
    
    
        /// <summary>
        ///   用於查詢當地語系化字串等的強類型資源類別。
        /// </summary>
        // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
        // 類別透過 ResGen 或 Visual Studio 這類工具。
        // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
        // (利用 /str 選項)，或重建您的 VS 專案。
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeagueSharp.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 {
        ///	&quot;\u003c&quot;: &quot;\u003c&quot;,
        ///	&quot;yasuo&quot;: &quot;\u72bd\u5bbf&quot;,
        ///  &quot;velkoz&quot;: &quot;\u5a01\u5bc7\u8332&quot;,
        ///  &quot;braum&quot;: &quot;\u5e03\u90ce\u59c6&quot;,
        ///  &quot;gnar&quot;: &quot;\u5436\u5152&quot;,
        ///  &quot;azir&quot;: &quot;\u963f\u7948\u723e&quot;,
        ///  &quot;kalista&quot;: &quot;\u514b\u9ece\u601d\u59b2&quot;,
        ///  &quot;rekSai&quot;: &quot;\u96f7\u73c2\u715e&quot;,
        ///  &quot;bard&quot;: &quot;\u5df4\u5fb7&quot;,
        ///  &quot;ekko&quot;: &quot;\u827e\u514b&quot;,
        ///  &quot;aatrox&quot;: &quot;\u5384\u85a9\u65af&quot;,
        ///  &quot;ahri&quot;: &quot;\u963f\u7483&quot;,
        ///  &quot;akali&quot;: &quot;\u963f\u5361\u8389&quot;,
        ///  &quot;alistar&quot;: &quot;\u4e9e\u6b77\u65af\u5854&quot;,
        ///  &quot;amumu&quot;: &quot;\u963f\u59c6\u59c6&quot;,
        ///  &quot;anivia&quot;: &quot;\u827e\u59ae\u7dad\u4e9e&quot;,
        ///  &quot;annie&quot;: &quot;\u5b89\u59ae&quot;,
        ///  &quot;ashe&quot;: &quot;\u827e\u5e0c&quot;,
        ///  &quot;blitzcrank&quot;: &quot;\u5e03\u91cc\u8328&quot;,
        ///  &quot;brand&quot;: &quot;\u5e03\u862d\u5fb7&quot;,
        ///  &quot;caitlyn&quot;: &quot;\u51f1\u7279\u7433&quot;,
        ///  &quot;cassiopeia&quot;: &quot;\u5361\u838e\u78a7\u96c5&quot;,
        ///  &quot;chogath&quot;: &quot;\u79d1\u52a0\u65af&quot;,
        ///  &quot;corki&quot;: &quot;\u5eab\u5947&quot;,
        ///  &quot;darius&quot;: &quot;\u9054\u745e\u65af&quot;,
        ///  &quot;diana&quot;: &quot;\u9edb\u5b89\u5a1c&quot;,
        ///  &quot;drmundo&... 的當地語系化字串。
        /// </summary>
        internal static string ChineseJson {
            get {
                return ResourceManager.GetString("ChineseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap CPActiveSlider {
            get {
                object obj = ResourceManager.GetObject("CPActiveSlider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap CPForm {
            get {
                object obj = ResourceManager.GetObject("CPForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap CPInactiveSlider {
            get {
                object obj = ResourceManager.GetObject("CPInactiveSlider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
